name: action di tommytommy
on: 
  push:
jobs: 
   name: machine_learning
   runs-on: ubuntu latest
   steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          sanviti
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install -r sanviti/requirements.txt
    - name: controlla la cartella sanviti
    - run: ls -laR sanviti
    - run: python sanviti/esame_ml.py 
    - name: carica modello addestrato come artifact
      uses: action/upload-artifact@v4
      with:
        name: modello-case
        path: sanviti/model.pkl




 